import formidable from "formidable";
import { createServiceClient } from "../../../../lib/supabase/server";
import { publishRelease } from "../../../../lib/publishRelease";
import { verifyApiToken } from "../../../../lib/verifyApiToken";

export const config = {
  api: { bodyParser: false },
};

// Non-interactive release publishing for CI/CD pipelines:
//   curl -X POST /api/ci/releases/create \
//     -H "Authorization: Bearer qap_..." \
//     -F platform=ios -F version=1.2.0 -F bundleId=com.company.app \
//     -F file=@app.ipa
// Bearer tokens aren't Supabase sessions, so project_role()/RLS can't
// resolve them — permission is instead the fact that the token exists,
// is unrevoked, and is scoped to exactly one project (see api_tokens'
// owner-only RLS on the *management* side; this endpoint itself always
// uses the service-role client, same trust model as the interactive
// endpoint after its own explicit role check).
export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).end();
    return;
  }

  const service = createServiceClient();
  const token = await verifyApiToken(service, req);
  if (!token) {
    res.status(401).json({ error: "Missing or invalid Authorization: Bearer <token> header" });
    return;
  }
  // Explicit kind check, not just the scope check below: an org token
  // publishing to a project chosen by request body would let one leaked
  // token publish to any project in the org. Belt-and-suspenders with
  // org_api_tokens.scope's DB-level 'read'-only constraint, which alone
  // would already reject this via the scope check — this makes the
  // rejection reason unambiguous rather than incidentally correct.
  if (token.kind !== "project") {
    res.status(403).json({ error: "Organization-scoped tokens can't publish releases — use a project token instead." });
    return;
  }
  if (token.scope !== "publish") {
    res.status(403).json({ error: "This token is read-only and cannot publish releases" });
    return;
  }

  const { data: creator } = await service.auth.admin.getUserById(token.created_by);
  const actorEmail = creator?.user?.email;
  if (!actorEmail) {
    res.status(500).json({ error: "Could not resolve the token's owner" });
    return;
  }

  const form = formidable({ maxFileSize: 500 * 1024 * 1024 });
  let fields, files;
  try {
    [fields, files] = await form.parse(req);
  } catch (e) {
    res.status(400).json({ error: "Could not parse upload: " + e.message });
    return;
  }

  const get = (f) => (Array.isArray(fields[f]) ? fields[f][0] : fields[f]);

  const result = await publishRelease({
    service,
    req,
    projectId: token.project_id,
    platform: get("platform"),
    version: get("version"),
    buildNumber: get("buildNumber") || null,
    bundleId: get("bundleId") || null,
    notes: get("notes") || null,
    webUrl: get("webUrl") || null,
    appNameInput: get("appName") || null,
    replace: get("replace") === "true" || get("replace") === "1",
    files,
    createdByUserId: token.created_by,
    actorEmail,
    activityDetailSuffix: ` (via CI token${token.label ? `: ${token.label}` : ""})`,
    channel: get("channel") || "production",
    scheduledFor: get("scheduledFor") || null,
    // Tokens can only be generated by a project owner (see
    // pages/api/projects/tokens/create.js), so a CI publish is
    // inherently an owner-equivalent action — never held for approval.
    publisherRole: "owner",
  });

  if (!result.ok) {
    res.status(result.status).json(result.body);
    return;
  }
  res.status(200).json({ releaseId: result.releaseId, status: result.status });
}
